# -*- coding: utf-8 -*-
"""IVF sharpener project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8sZqsuIhXGvXjMK4XdSMMreXRBP6yvc
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('IVF_Data_Driven_Insights_Synthetic_Dataset.csv')

df.head()

df.shape

df.info()

df.describe()

df.isnull().sum()

# Fill missing numeric values with the median (simple and safe method)
df['AMH_ng_mL'] = df['AMH_ng_mL'].fillna(df['AMH_ng_mL'].mean())
df['Endometrial_Thickness_mm'] = df['Endometrial_Thickness_mm'].fillna(df['Endometrial_Thickness_mm'].mean())
df['Cycle_Cost_INR'] = df['Cycle_Cost_INR'].fillna(df['Cycle_Cost_INR'].median())

# Confirm no missing values remain
df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates()

# Simple outlier check using boxplot
plt.figure(figsize=(8,4))
sns.boxplot(x=df['Cycle_Cost_INR'])
plt.title('Boxplot - Cycle Cost (check for outliers)')
plt.show()

# Detect outliers using IQR method (easy formula)
Q1 = df['Cycle_Cost_INR'].quantile(0.25)
Q3 = df['Cycle_Cost_INR'].quantile(0.75)
IQR = Q3 - Q1
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[(df['Cycle_Cost_INR'] < lower_limit) | (df['Cycle_Cost_INR'] > upper_limit)]
print("Number of outliers in Cycle_Cost_INR:", len(outliers))

# Simple outlier check using boxplot
plt.boxplot(df["AMH_ng_mL"])

plt.title("AMH Outliers")

plt.show()

Q1 = df["AMH_ng_mL"].quantile(0.25)

Q3 = df["AMH_ng_mL"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR

upper = Q3 + 1.5 * IQR

outliers = df[
    (df["AMH_ng_mL"] < lower)
    |
    (df["AMH_ng_mL"] > upper)
]

len(outliers)

#Statistical summary
df.describe()

#Categorical summary
df.describe(include="object")

#Count the age groups
df["Age_Group"].value_counts()

#Count the diagnoses
df["Diagnosis"].value_counts()

#Calculate the pregnancy rate
df["Clinical_Pregnancy"].value_counts()

# Filtering: Select only patients with Live Birth = Yes
success_cases = df[df['Live_Birth'] == 'Yes']
print(success_cases.shape)
success_cases

# Filtering with multiple conditions: Age above 35 AND Live Birth = Yes
older_success = df[(df['Patient_Age'] > 35) & (df['Live_Birth'] == 'Yes')]
older_success.head()

# Sorting: Top 10 cycles with highest Cycle Cost
df.sort_values(by='Cycle_Cost_INR', ascending=False).head(10)

# Sorting: Lowest AMH values first (multiple columns)
df.sort_values(by=['AMH_ng_mL', 'Patient_Age'], ascending=[True, False]).head(10)

#Average AMH according to age group
df.groupby(
    "Age_Group"
)["AMH_ng_mL"].mean()

# Simple GroupBy: Average AMH per Diagnosis
df.groupby('Diagnosis')['AMH_ng_mL'].mean()

# GroupBy with multiple aggregations
df.groupby('Age_Group')['Cycle_Cost_INR'].agg(['mean', 'min', 'max', 'count'])

# GroupBy with multiple columns

df.groupby('Diagnosis')['AMH_ng_mL'].mean()

# GroupBy + custom summary table
summary = df.groupby('Diagnosis').agg(
    Avg_Age=('Patient_Age', 'mean'),
    Avg_Cost=('Cycle_Cost_INR', 'mean'),
    Live_Birth_Rate=('Live_Birth', 'mean'),
    Total_Cycles=('Cycle_ID', 'count')
)
summary

####################   Visualization    #####################

# Age distribution
plt.hist(df["Patient_Age"])


plt.title("Patient Age Distribution")


plt.xlabel("Age")


plt.ylabel("Frequency")


plt.show()

## Diagnosis distribution
df["Diagnosis"].value_counts().plot(
    kind="bar"
)


plt.title("Diagnosis Distribution")


plt.show()

## Fertilization method
df["Fertilization_Method"].value_counts().plot(
    kind="bar"
)


plt.title(
    "Fertilization Method"
)


plt.show()

##Correlation between variables
df[
    [
        "Patient_Age",
        "AMH_ng_mL",
        "AFC_Count"
    ]
].corr()

df_clean = df.dropna()

# 1. Ensure the folder exists
import os
import pandas as pd
output_dir = 'C:/SQLData'
os.makedirs(output_dir, exist_ok=True)

# 2. Save the CSV
df_clean.to_csv(os.path.join(output_dir, 'IVF_Data_Cleaned.csv'), index=False)
print("File saved successfully!")

df_clean.to_csv(r'C:\SQLData\IVF_Data_Cleaned.csv', index=False)

from google.colab import files

# Save to CSV in Colab workspace
df_clean.to_csv('IVF_Data_Cleaned.csv', index=False)

# Trigger browser download
files.download('IVF_Data_Cleaned.csv')